"use client";

import {
  ChartBar,
  FileText,
  Plug,
  Globe,
  CurrencyDollar,
  TrendUp,
  Clock,
  Brain,
  Buildings,
  Newspaper,
  ShoppingCart,
  Briefcase,
  ClipboardText,
  ArrowsClockwise,
  Robot,
  ProjectorScreen,
  Envelope,
  CheckCircle,
  Star,
  Users,
  Lightning,
  Target,
  ChartLine,
  Database,
  Book,
  Bell,
  Lock,
  Broadcast,
  Desktop,
  Package,
  ChatCircle,
  Link as LinkIcon,
  Tag,
  PaintBrush,
  Factory,
  Storefront,
  TShirt,
  GlobeHemisphereEast,
  ArrowLeft,
  ArrowRight,
  Check,
  Info,
  Warning,
  Question,
  Gear,
  House,
  MagnifyingGlass,
  Download,
  Upload,
  Calendar,
  Phone,
  MapPin,
  LinkedinLogo,
  GithubLogo,
  TwitterLogo,
  Play,
  Pause,
  CaretDown,
  CaretUp,
  CaretRight,
  CaretLeft,
  List,
  X,
  Plus,
  Minus,
  PencilSimple,
  Trash,
  Eye,
  EyeSlash,
  Copy,
  Share,
  Heart,
  Bookmark,
  Funnel,
  SortAscending,
  SortDescending,
  DotsThree,
  Sparkle,
  Handshake,
  Certificate,
  Key,
} from "@phosphor-icons/react";
import type { Icon } from "@phosphor-icons/react";

// Icon mapping for data-driven components
export const iconMap: Record<string, Icon> = {
  // Products
  "chart-bar": ChartBar,
  "file-text": FileText,
  plug: Plug,

  // Data categories
  globe: Globe,
  "currency-dollar": CurrencyDollar,
  "trend-up": TrendUp,
  clock: Clock,
  brain: Brain,
  buildings: Buildings,
  newspaper: Newspaper,
  "shopping-cart": ShoppingCart,
  briefcase: Briefcase,
  "clipboard-text": ClipboardText,

  // Consulting services
  "arrows-clockwise": ArrowsClockwise,
  robot: Robot,
  "projector-screen": ProjectorScreen,

  // General
  envelope: Envelope,
  "check-circle": CheckCircle,
  star: Star,
  users: Users,
  lightning: Lightning,
  target: Target,
  "chart-line": ChartLine,
  database: Database,
  book: Book,
  bell: Bell,
  lock: Lock,
  broadcast: Broadcast,
  desktop: Desktop,
  package: Package,
  "chat-circle": ChatCircle,
  link: LinkIcon,
  tag: Tag,
  "paint-brush": PaintBrush,
  factory: Factory,
  storefront: Storefront,
  "t-shirt": TShirt,
  "globe-hemisphere-east": GlobeHemisphereEast,

  // Arrows & navigation
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "caret-down": CaretDown,
  "caret-up": CaretUp,
  "caret-right": CaretRight,
  "caret-left": CaretLeft,

  // Status
  check: Check,
  info: Info,
  warning: Warning,
  question: Question,

  // Actions
  gear: Gear,
  house: House,
  "magnifying-glass": MagnifyingGlass,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  phone: Phone,
  "map-pin": MapPin,
  play: Play,
  pause: Pause,
  list: List,
  x: X,
  plus: Plus,
  minus: Minus,
  "pencil-simple": PencilSimple,
  trash: Trash,
  eye: Eye,
  "eye-slash": EyeSlash,
  copy: Copy,
  share: Share,
  heart: Heart,
  bookmark: Bookmark,
  funnel: Funnel,
  "sort-ascending": SortAscending,
  "sort-descending": SortDescending,
  "dots-three": DotsThree,

  // Social
  linkedin: LinkedinLogo,
  github: GithubLogo,
  twitter: TwitterLogo,

  // Auth
  key: Key,

  // Special
  sparkle: Sparkle,
  handshake: Handshake,
  certificate: Certificate,
};

// Helper component to render icons by key
interface IconByKeyProps {
  name: string;
  size?: number;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
  className?: string;
  style?: React.CSSProperties;
}

export function IconByKey({
  name,
  size = 24,
  weight = "duotone",
  className,
  style,
}: IconByKeyProps) {
  const IconComponent = iconMap[name];
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in iconMap`);
    return null;
  }
  return (
    <IconComponent
      size={size}
      weight={weight}
      className={className}
      style={style}
    />
  );
}

// Re-export commonly used icons for direct import
export {
  ChartBar,
  FileText,
  Plug,
  Globe,
  CurrencyDollar,
  TrendUp,
  Clock,
  Brain,
  Buildings,
  Newspaper,
  ShoppingCart,
  Briefcase,
  ClipboardText,
  ArrowsClockwise,
  Robot,
  ProjectorScreen,
  Envelope,
  CheckCircle,
  Star,
  Users,
  Lightning,
  Target,
  ChartLine,
  Database,
  Book,
  Bell,
  Lock,
  Broadcast,
  Desktop,
  Package,
  ChatCircle,
  LinkIcon,
  Tag,
  PaintBrush,
  Factory,
  Storefront,
  TShirt,
  GlobeHemisphereEast,
  ArrowLeft,
  ArrowRight,
  Check,
  Info,
  Warning,
  Question,
  Gear,
  House,
  MagnifyingGlass,
  Download,
  Upload,
  Calendar,
  Phone,
  MapPin,
  LinkedinLogo,
  GithubLogo,
  TwitterLogo,
  Play,
  Pause,
  CaretDown,
  CaretUp,
  CaretRight,
  CaretLeft,
  List,
  X,
  Plus,
  Minus,
  PencilSimple,
  Trash,
  Eye,
  EyeSlash,
  Copy,
  Share,
  Heart,
  Bookmark,
  Funnel,
  SortAscending,
  SortDescending,
  DotsThree,
  Sparkle,
  Handshake,
  Certificate,
  Key,
};

export type { Icon };
